### ISSUE TITLE
Only commit your packages

### ISSUE THREAD

**Issue by airfield20** [sxy-sun/ROS-Turtlesim#1]
The standard ros workflow requires you only to commit your packages to the repository. Not the entire catkin workspace.
Look at these other ros github repos as an example.

https://github.com/Bedestrian/B3-ros_pkg_SimulationDesktop

https://github.com/ros-controls/ros_control

**Comment by sxy-sun** [comment]
Repo updated.
Removed the catkin workspace, only kept two packages in it. Added install script which can be used to setup the catkin space locally.
